### ISSUE TITLE
Lexer error when using an '#include'

### ISSUE THREAD

**Issue by stofi** [NaridaL/glsl-language-toolkit#11]
Hi, thanks for this plugin.

I found an issue when trying to format a file that has a '#include' directive. Prettier fails with a lexer error:
```
[error] test.glsl: Error: LEXER ERROR: unexpected character: ->"<- at offset: 9, skipped 1 characters.:
```

Here is a repo reproducing the bug:
https://github.com/stofi/prettier-plugin-glsl-include-bug

**Comment by NaridaL** [comment]
Hi @stofi , can I ask in what context you are using `#include` ?

As far as I know it is not part of glsl.

> 
> Preprocessor
> There is a preprocessor that processes the source strings as part of the compilation process.
> The complete list of preprocessor directives is as follows.
> #
> #define
> #undef
> #if
> #ifdef
> #ifndef
> #else
> #elif
> #endif
> #error
> #pragma
> #extension
> #line
> The following operator is also available
> defined
> Note that the version directive is not considered to be a preprocessor directive and so is not listed here.
> Each number sign (#) can be preceded in its line only by spaces or horizontal tabs. It may also be
> followed by spaces and horizontal tabs, preceding the directive. Each directive is terminated by a new-
> line. Preprocessing does not change the number or relative location of new-lines in a source string.
> The number sign (#) on a line by itself is ignored. Any directive not listed above will cause an error.

The parser currently follows the spec and throws an error for an unknown directive.

**Comment by NaridaL** [comment]
@stofi What library is adding this extension? I'm not opposed to adding it.

**Comment by stofi** [comment]
@NaridaL Hi, sorry for not getting back to you earlier. My bad I thought the import is part of the spec. I am using it with [vite-plugin-glsl](https://github.com/UstymUkhman/vite-plugin-glsl) and (lygia)[https://github.com/patriciogonzalezvivo/lygia]

**Comment by NaridaL** [comment]
@stofi Thanks for the info. According to the lygia docs, the #include directive is based on some glsl language feature. I wasn't able to find a spec for it though. In any case, I've added it. Give v0.0.9 a try.
