### ISSUE TITLE
[prettier-plugin-glsl] `// prettier-ignore` not work

### ISSUE THREAD

**Issue by mantou132** [NaridaL/glsl-language-toolkit#13]
test.frag:

```glsl
// prettier-ignore
const mat3 YIQ2RGB = mat3(1.000, 1.000, 1.000,
                          0.956,-0.272,-1.106,
                          0.621,-0.647, 1.703);
```
will be formatted into one line each time save

**Comment by NaridaL** [comment]
Hmm I guess I need to figure out how to integrate that prettier feature.

In this case it probably makes more sense to support this type of formatting for literal matrices.

what do you think:

![grafik](https://user-images.githubusercontent.com/10828874/229296419-ca3280d8-bb1a-47b5-91d7-d54d30808d21.png)

**Comment by mantou132** [comment]
It would be nice if it could be formatted for the grid.

`// prettier-ignore` has another function to keep it consistent with other people's code.

thanks for your work

**Comment by NaridaL** [comment]
I added `// prettier-ignore`, there was just a plugin callback missing. I've also implemented the grid format for literals. Give it a try with version 0.0.10!
