### ISSUE TITLE
Support for Prettier v3

### ISSUE THREAD

**Issue by benc-uk** [NaridaL/glsl-language-toolkit#16]
Hi, thanks for this plugin it's a life saver! and one of the few "not crazy" way to get GLSL linting working 👏

I notice that Prettier have just updated to v3 and this plugin complains about dependencies

I think there's some breaking changes for plugin developers too :(
https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F

**Comment by NaridaL** [comment]
Yeah, I had a quick look before, but the migration is not entirely trivial as I was using the markdown formatter for comments, which no longer works directly as it is now async. I'll take another look.

Interesting that you say this is useful for linting. I was actually working on some more in depth type checks (for a vs code extension), but I don't use glsl much these days, plus it looks like the Web is moving towards webgpu anyways.

**Comment by NaridaL** [comment]
v0.1.2 works with prettier v3... but formatting comments as markdown is disabled for now.

note that prettier 3 needs the plugins to be listed explicitly, so you will need to to add "plugins": ["prettier-plugin-glsl"] to your prettier config

**Comment by benc-uk** [comment]
Working well here with 0.1.2 and Prettier v3.0.3

**Comment by disambiguator** [comment]
Thank you! Maybe a note in the README for others coming to this would be great.

**Comment by NaridaL** [comment]
added a note in the readme.
