### ISSUE TITLE
[prettier-plugin-glsl] Breaks scientific notation on some numbers.

### ISSUE THREAD

**Issue by seanpkent** [NaridaL/glsl-language-toolkit#17]
Using prettier-plugin-glsl 0.1.2 + prettier 3.0.2
Some numbers using scientific notation will have ending `0` removed.
For example, `float e = 1.0e-10;` will become `float e = 1.0e-1;` after formatting with prettier-plugin-glsl.

**Comment by NaridaL** [comment]
yep, that's not supposed to happen. Pushed a fix, publishing now...

**Comment by NaridaL** [comment]
please test 0.1.3

**Comment by seanpkent** [comment]
@NaridaL I tested 0.1.3 and the issue is fixed. Thank you!
