### ISSUE TITLE
[prettier-plugin-glsl] Error when parsing "precision mediump float"

### ISSUE THREAD

**Issue by SeiyaCooper** [NaridaL/glsl-language-toolkit#19]
Hi, this bug happens when using a fragement shader with `precision` declaration.
For instance, this code:
```
precision mediump float;
// nothing
```
will fail bacause of this:
```
[error] test.frag: SyntaxError: Missing semicolon. (1:10)
[error] > 1 | precision mediump float;
[error]     |          ^
[error]   2 |
[error]   3 | // nothing
```

Also, I noticed that this only happens when the file extension is `.frag`, if its `glsl`, this would not happen.

**Comment by NaridaL** [comment]
Hi Seiya,, cool that you're using this :-)

There's an issue for .frag files, prettier treats them as javascript files for some reason.
Please try the workaround described in the readme: https://github.com/NaridaL/glsl-language-toolkit/tree/main/packages/prettier-plugin-glsl#installation (add `"overrides": [{"files": ["*.frag"], "options": {"parser": "glsl-parser"}}]` to your prettier config).

**Comment by SeiyaCooper** [comment]
Thats working, sorry about the inconvenience. Thanks a lot ;)
