### ISSUE TITLE
#include <xyz> does not parse

### ISSUE THREAD

**Issue by phuhl** [NaridaL/glsl-language-toolkit#20]
In threejs shaders often have #include statements that are differen from the include in #12 as they are not followed by a string but by `<some_text>`. This does not parse, currently. Here is an example:

```glsl
uniform vec3 color;
uniform sampler2D tDiffuse;

varying vec4 vUv;

float blendOverlay(float base, float blend) {
  return base < 0.5
    ? 2.0 * base * blend
    : 1.0 - 2.0 * (1.0 - base) * (1.0 - blend);

}

vec3 blendOverlay(vec3 base, vec3 blend) {
  return vec3(
    blendOverlay(base.r, blend.r),
    blendOverlay(base.g, blend.g),
    blendOverlay(base.b, blend.b)
  );

}

void main() {
  vec4 base = texture2DProj(tDiffuse, vUv);
  gl_FragColor = vec4(blendOverlay(base.rgb, color), 1.0);

  #include <tonemapping_fragment>
  #include <colorspace_fragment>

}
```

The example is taken from https://github.com/mrdoob/three.js/blob/master/examples/jsm/objects/Refractor.js

I am not sure what the language spec behind this is, but if this include style could be parsed correctly, that would be a huge help :)

**Comment by NaridaL** [comment]
Yeah, seems to be non-spec addition inspired by C. I wasn't able to find any documentation about it, but it seems to be implemented here:

https://github.com/mrdoob/three.js/blob/98616257db739e50513437c6913156c17a6d40e4/src/renderers/webgl/WebGLProgram.js#L239

I've gone ahead and added support for it, try v0.2.0.

**Comment by phuhl** [comment]
Works perfect. Thank you!
